unstable_features = true
edition = "2018"
version = "Two"
wrap_comments = true
comment_width = 120
max_width = 120
imports_granularity="Preserve"
newline_style = "Unix"
struct_lit_single_line = false
